Repository vianetwork/via-core, pull requests merged in 2025-02, with the labels that each got.

#104 Feat/via add verify unsigned tx to verifier
  core/lib/via_btc_client/src/withdrawal_builder/mod.rs
  core/node/node_framework/src/implementations/layers/via_verifier/verifier.rs
  via_verifier/lib/verifier_dal/.sqlx/query-4f3219a13e972e4c7b13af9d22c55e871be4ac71acac33d4662af5cfc4c6bff9.json
  via_verifier/lib/verifier_dal/src/via_votes_dal.rs
  via_verifier/node/withdrawal_service/src/coordinator/api_impl.rs
  via_verifier/node/withdrawal_service/src/utils.rs
  via_verifier/node/withdrawal_service/src/verifier/mod.rs
Labels: enhancement

#115 clean: remove un used verification service crate
  via_verifier/node/verification_service/Cargo.toml
  via_verifier/node/verification_service/src/lib.rs
Labels: refactor

#114 remove: retry logic from btc_sender
  core/lib/dal/.sqlx/query-939ac2a27e3844db1e4606e2338a2da09357ece059755139e698acbc050a7673.json
  core/lib/dal/src/btc_sender_dal.rs
  core/lib/via_btc_client/examples/bootstrap.rs
  core/lib/via_btc_client/examples/deposit.rs
  core/lib/via_btc_client/examples/inscriber.rs
  core/lib/via_btc_client/examples/verify_batch.rs
  core/lib/via_btc_client/src/inscriber/mod.rs
  core/lib/via_btc_client/src/inscriber/test_utils.rs
  core/lib/via_btc_client/src/types.rs
  core/node/via_btc_sender/src/btc_inscription_aggregator.rs
  core/node/via_btc_sender/src/btc_inscription_manager.rs
  core/node/via_btc_sender/src/tests/btc_inscription_manager_test.rs
  via_verifier/lib/verifier_dal/.sqlx/query-939ac2a27e3844db1e4606e2338a2da09357ece059755139e698acbc050a7673.json
  via_verifier/lib/verifier_dal/src/via_btc_sender_dal.rs
  via_verifier/node/verification_service/Cargo.toml
  via_verifier/node/verification_service/src/lib.rs
  via_verifier/node/via_btc_sender/src/btc_inscription_manager.rs
Labels: refactor

#119 Feat/via verifier validate op priority
  Cargo.lock
  Cargo.toml
  via_verifier/lib/verifier_dal/.sqlx/query-175807bfd3b6618ab60ede8cb56ddc773bf8e85190606d1b6f2203ce8b5aba2e.json
  via_verifier/lib/verifier_dal/.sqlx/query-1c5df79bec4f47dc94562f5d27fbeeda15ca4daf5620896833c3cdd4c909a156.json
  via_verifier/lib/verifier_dal/.sqlx/query-c2f1e15f46b72570d02c7b8be08024ec90890f94199b039933296c3f99ba63bf.json
  via_verifier/lib/verifier_dal/.sqlx/query-ea3062d8c4eb8f234ba6fbc145734c78fcf487984d098ef103bb228a787e6e2e.json
  via_verifier/lib/verifier_dal/.sqlx/query-ed6c76995db0b440fcce87a2acdf5f2c1e476cdcbcca9a61c1af5f0234fc22a5.json
  via_verifier/lib/verifier_dal/migrations/20250207164238_via_add_transactions_dal.down.sql
  via_verifier/lib/verifier_dal/migrations/20250207164238_via_add_transactions_dal.up.sql
  via_verifier/lib/verifier_dal/src/lib.rs
  via_verifier/lib/verifier_dal/src/via_transactions_dal.rs
  via_verifier/lib/via_da_client/Cargo.toml
  via_verifier/lib/via_da_client/src/lib.rs
  via_verifier/lib/via_da_client/src/pubdata.rs
  via_verifier/lib/via_da_client/src/types.rs
  via_verifier/lib/via_withdrawal_client/Cargo.toml
  via_verifier/lib/via_withdrawal_client/src/client.rs
  via_verifier/lib/via_withdrawal_client/src/lib.rs
  via_verifier/lib/via_withdrawal_client/src/withdraw.rs
  via_verifier/node/via_btc_watch/src/lib.rs
  via_verifier/node/via_btc_watch/src/message_processors/l1_to_l2.rs
  via_verifier/node/via_btc_watch/src/message_processors/mod.rs
  via_verifier/node/via_btc_watch/src/metrics.rs
  via_verifier/node/via_zk_verifier/Cargo.toml
  via_verifier/node/via_zk_verifier/src/lib.rs
Labels: enhancement

#122 Refactor/via verifier and coordinator
  Cargo.lock
  Cargo.toml
  core/lib/via_btc_client/src/lib.rs
  core/node/node_framework/Cargo.toml
  core/node/node_framework/src/implementations/layers/via_verifier/coordinator_api.rs
  core/node/node_framework/src/implementations/layers/via_verifier/verifier.rs
  infrastructure/via/src/config.ts
  via_verifier/lib/via_musig2/Cargo.toml
  via_verifier/lib/via_musig2/examples/coordinator.rs
  via_verifier/lib/via_musig2/src/lib.rs
  via_verifier/lib/via_musig2/src/withdrawal_builder/mod.rs
  via_verifier/lib/via_verifier_types/Cargo.toml
  via_verifier/lib/via_verifier_types/src/lib.rs
  via_verifier/lib/via_verifier_types/src/transaction.rs
  via_verifier/lib/via_verifier_types/src/withdrawal.rs
  via_verifier/lib/via_withdrawal_client/Cargo.toml
  via_verifier/lib/via_withdrawal_client/src/client.rs
  via_verifier/lib/via_withdrawal_client/src/withdraw.rs
  via_verifier/node/via_verifier_coordinator/Cargo.toml
  via_verifier/node/via_verifier_coordinator/src/auth.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/api.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/api_decl.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/api_impl.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/auth_middleware.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/error.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/mod.rs
  via_verifier/node/via_verifier_coordinator/src/lib.rs
  via_verifier/node/via_verifier_coordinator/src/sessions/mod.rs
  via_verifier/node/via_verifier_coordinator/src/sessions/session_manager.rs
  via_verifier/node/via_verifier_coordinator/src/sessions/withdrawal.rs
  via_verifier/node/via_verifier_coordinator/src/traits.rs
  via_verifier/node/via_verifier_coordinator/src/types.rs
  via_verifier/node/via_verifier_coordinator/src/utils.rs
  via_verifier/node/via_verifier_coordinator/src/verifier/mod.rs
  via_verifier/node/withdrawal_service/src/coordinator/api_impl.rs
  via_verifier/node/withdrawal_service/src/types.rs
Labels: refactor

#125 feat: add previous l1 batch to the da inscription
  core/lib/dal/.sqlx/query-81106abcd933c2eb69ee031d25b099e6b797046ce56813a9b3fc30c8ab27bda8.json
  core/lib/dal/.sqlx/query-a0985c05837aa7cb9729a3dbf0ed15b89c17574b2d51c5c957eb5833a03574bf.json
  core/lib/dal/.sqlx/query-e8938920560d22ecc0dd5d6cfe38ea39f34811978f71d421accc52916de1c952.json
  core/lib/dal/.sqlx/query-fc2a5e4a5522d4869c5a9d864c32bb2d8f8b05a77c9c80a4759ec757d2024bf2.json
  core/lib/dal/src/models/storage_btc_block.rs
  core/lib/dal/src/via_blocks_dal.rs
  core/lib/types/src/btc_block.rs
  core/lib/via_btc_client/examples/inscriber.rs
  core/lib/via_btc_client/src/indexer/mod.rs
  core/lib/via_btc_client/src/indexer/parser.rs
  core/lib/via_btc_client/src/inscriber/mod.rs
  core/lib/via_btc_client/src/inscriber/script_builder.rs
  core/lib/via_btc_client/src/types.rs
  core/node/via_btc_sender/src/aggregator.rs
  core/node/via_btc_sender/src/tests/aggregator_test.rs
  core/node/via_btc_sender/src/tests/utils.rs
  via_verifier/node/via_zk_verifier/src/lib.rs
Labels: enhancement

#127 Feat/via musig2 transaction builder and utxo context
  Cargo.lock
  core/lib/via_btc_client/src/inscriber/test_utils.rs
  core/node/node_framework/src/implementations/layers/via_verifier/coordinator_api.rs
  core/node/node_framework/src/implementations/layers/via_verifier/verifier.rs
  via_verifier/lib/via_musig2/examples/coordinator.rs
  via_verifier/lib/via_musig2/src/lib.rs
  via_verifier/lib/via_musig2/src/transaction_builder.rs
  via_verifier/lib/via_musig2/src/utxo_manager.rs
  via_verifier/lib/via_withdrawal_client/Cargo.toml
  via_verifier/node/via_verifier_coordinator/src/coordinator/api.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/api_decl.rs
  via_verifier/node/via_verifier_coordinator/src/sessions/session_manager.rs
  via_verifier/node/via_verifier_coordinator/src/sessions/withdrawal.rs
  via_verifier/node/via_verifier_coordinator/src/verifier/mod.rs
Labels: enhancement, refactor

#133 fix: replace context with with_context and remove not required context
  core/node/via_btc_sender/src/btc_inscription_aggregator.rs
  core/node/via_btc_sender/src/btc_inscription_manager.rs
  core/node/via_btc_watch/src/lib.rs
  via_verifier/lib/verifier_dal/src/via_btc_sender_dal.rs
  via_verifier/lib/via_da_client/src/pubdata.rs
  via_verifier/lib/via_da_client/src/types.rs
  via_verifier/lib/via_musig2/src/transaction_builder.rs
  via_verifier/lib/via_withdrawal_client/src/withdraw.rs
  via_verifier/node/via_btc_sender/src/btc_inscription_manager.rs
  via_verifier/node/via_btc_sender/src/btc_vote_inscription.rs
  via_verifier/node/via_btc_watch/src/lib.rs
  via_verifier/node/via_verifier_coordinator/src/auth.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/api.rs
  via_verifier/node/via_verifier_coordinator/src/coordinator/api_decl.rs
  via_verifier/node/via_verifier_coordinator/src/sessions/withdrawal.rs
  via_verifier/node/via_verifier_coordinator/src/utils.rs
  via_verifier/node/via_verifier_coordinator/src/verifier/mod.rs
  via_verifier/node/via_zk_verifier/src/lib.rs
Labels: refactor

#137 Refactor/via improve sequencer db schema
  core/lib/dal/.sqlx/query-110825e736943e4ef68110e8d7af3af3edce16051e8987a27ea207bfe9b65502.json
  core/lib/dal/.sqlx/query-19e7ce055b5e5d394bcf82036e5f82ddd1ec26360c47ff369ea191029c0d34ca.json
  core/lib/dal/.sqlx/query-1b66d7cbab7d7cf8ab40e2524776c5f830c8f5a47772ef100e747b534fe4df18.json
  core/lib/dal/.sqlx/query-2082d20e3b547a7385c174892d96857119c57c7ff5194a546d24fec0e3cf3059.json
  core/lib/dal/.sqlx/query-3229aefe26d77c22cee31dd506cd62244613761e41e811705611d75fbe48ad1a.json
  core/lib/dal/.sqlx/query-50317cd02daa34f645c53abedd40a3601bad164df280127c4aa4dce2ddd414d7.json
  core/lib/dal/.sqlx/query-680135945c2c49d595d8bb1bef40c19e79c60a87b61faa3006740cb47932d6ad.json
  core/lib/dal/.sqlx/query-779aa8d684219a02ad2cab958e2040cccb590ec0c07ea7ffa931558725581e38.json
  core/lib/dal/.sqlx/query-81106abcd933c2eb69ee031d25b099e6b797046ce56813a9b3fc30c8ab27bda8.json
  core/lib/dal/.sqlx/query-fc2a5e4a5522d4869c5a9d864c32bb2d8f8b05a77c9c80a4759ec757d2024bf2.json
  core/lib/dal/migrations/20240906134623_add_via_btc_inscription_requests.up.sql
  core/lib/dal/src/lib.rs
  core/lib/dal/src/models/storage_btc_block.rs
  core/lib/dal/src/models/storage_btc_inscription_request.rs
  core/lib/dal/src/via_blocks_dal.rs
  core/lib/dal/src/via_btc_sender_dal.rs
  core/lib/dal/src/via_transactions_dal.rs
  core/lib/dal/src/via_votes_dal.rs
  core/lib/types/src/lib.rs
  core/lib/types/src/via_btc_sender.rs
  core/node/via_btc_sender/src/aggregator.rs
  core/node/via_btc_sender/src/btc_inscription_aggregator.rs
  core/node/via_btc_sender/src/btc_inscription_manager.rs
  core/node/via_btc_sender/src/tests/aggregator_test.rs
  core/node/via_btc_sender/src/tests/btc_inscription_aggregator_test.rs
  core/node/via_btc_sender/src/tests/btc_inscription_manager_test.rs
  core/node/via_btc_sender/src/tests/utils.rs
  core/node/via_btc_watch/src/message_processors/votable.rs
  via_verifier/lib/verifier_dal/src/models/storage_btc_inscription_request.rs
  via_verifier/lib/verifier_dal/src/via_btc_sender_dal.rs
  via_verifier/node/via_btc_sender/src/btc_inscription_manager.rs
Labels: refactor

#136 Via documentation
  README.md
  architecture.png
  docs/guides/via.md
  docs/via_guides/architecture.md
  docs/via_guides/development.md
  infrastructure/via/src/contract.ts
  infrastructure/via/src/index.ts
  infrastructure/via/src/up.ts
  via-playground/README.md
  viaArchitecture.png
  via_verifier/README.md
Labels: documentation

#139 fix: via tests
  core/node/via_block_reverter/src/tests.rs
  core/node/via_state_keeper/src/io/tests/tester.rs
  core/node/via_state_keeper/src/tests/mod.rs
  infrastructure/via/src/database.ts
  infrastructure/via/src/test/test.ts
  via_verifier/lib/verifier_dal/src/tests/mod.rs
Labels: bug
