Repository vianetwork/via-core, pull requests merged in 2025-03, with the labels that each got.

#140 Docs/data-flow-in-via
  README.md
  docs/via_guides/data-flow.md
Labels: documentation

#143 fix: clean db after rollback
  via_verifier/lib/verifier_dal/.sqlx/query-33de7fc18e8d8a1b1184a0534b6d39997878f0e9c55451dd78aad781215d0c5b.json
  via_verifier/lib/verifier_dal/.sqlx/query-cae197d9d80d699cfad334172df98ce87169b9f6a875bb27b06dcfde5f6b48cc.json
  via_verifier/lib/verifier_dal/.sqlx/query-ef14cb4ebc117043413858ff7c66052f483736c9c2dba8a8b403daf39262886c.json
  via_verifier/lib/verifier_dal/src/tests/mod.rs
  via_verifier/lib/verifier_dal/src/via_votes_dal.rs
  via_verifier/node/via_zk_verifier/src/lib.rs
Labels: bug

#142 fix: update status l1 deposits after rollback
  via_verifier/lib/verifier_dal/.sqlx/query-33de7fc18e8d8a1b1184a0534b6d39997878f0e9c55451dd78aad781215d0c5b.json
  via_verifier/lib/verifier_dal/.sqlx/query-cae197d9d80d699cfad334172df98ce87169b9f6a875bb27b06dcfde5f6b48cc.json
  via_verifier/lib/verifier_dal/.sqlx/query-ef14cb4ebc117043413858ff7c66052f483736c9c2dba8a8b403daf39262886c.json
  via_verifier/lib/verifier_dal/src/tests/mod.rs
  via_verifier/lib/verifier_dal/src/via_votes_dal.rs
  via_verifier/node/via_zk_verifier/src/lib.rs
Labels: bug

#145 chore: update the contract binaries
  etc/multivm_bootloaders/vm_bitcoin/fee_estimate.yul/fee_estimate.yul.zbin
  etc/multivm_bootloaders/vm_bitcoin/gas_test.yul/gas_test.yul.zbin
  etc/multivm_bootloaders/vm_bitcoin/playground_batch.yul/playground_batch.yul.zbin
  etc/multivm_bootloaders/vm_bitcoin/proved_batch.yul/proved_batch.yul.zbin
Labels: bug

#154 feat: add governance address to the bootstrap inscription
  core/lib/via_btc_client/DEV.md
  core/lib/via_btc_client/examples/bootstrap.rs
  core/lib/via_btc_client/src/indexer/mod.rs
  core/lib/via_btc_client/src/indexer/parser.rs
  core/lib/via_btc_client/src/inscriber/script_builder.rs
  core/lib/via_btc_client/src/types.rs
Labels: enhancement
